sonar.projectKey=calculator
sonar.projectName=Calculator
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
# Generate a token from SonarQube web interface and replace it here
sonar.login=squ_100480f66222d99b6b59631b5bbb91ca0f4e3c06
