sonar.projectKey=calculator
sonar.projectName=Calculator
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
# Generate a token from SonarQube web interface and replace it here
sonar.login=squ_d98bda1a6884f2dc425ac6531d33287cfec400d3
